package main

import (
	"bytes"
	"context"
	"fmt"
	"harnessforge/internal/safefile"
	"harnessforge/internal/securityboundary"
	"harnessforge/internal/skills/application"
	"os"
	"path/filepath"
	"strings"

	"go.yaml.in/yaml/v3"
)

const generatedSetupMarker = "<!-- Generated by HarnessForge."

func classifySetupOutputs(root string, files []setupOutputFile) error {
	for index := range files {
		file := &files[index]
		if !safeSetupTarget(file.Path) {
			return fmt.Errorf("unsafe setup target %q", file.Path)
		}
		path := filepath.Join(root, filepath.FromSlash(file.Path))
		info, err := os.Lstat(path)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("refusing to replace non-regular %s", file.Path)
		}
		original, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		switch file.Path {
		case ".harness/harness.yaml":
			if !starterHarness(original) {
				return fmt.Errorf("%s already contains a configured harness; use the existing configuration", file.Path)
			}
		case "AGENTS.md", "CLAUDE.md":
			if !bytes.HasPrefix(original, []byte(generatedSetupMarker)) {
				file.Content = append(append(append([]byte(nil), original...), []byte("\n\n")...), file.Content...)
				file.Append = true
			}
		default:
			return fmt.Errorf("%s already exists; refusing to replace it", file.Path)
		}
		file.Replace = true
		file.Original = original
	}
	return nil
}

func starterHarness(data []byte) bool {
	var value map[string]any
	if err := yaml.Unmarshal(data, &value); err != nil {
		return false
	}
	if len(value) != 2 {
		return false
	}
	if _, ok := value["version"]; !ok {
		return false
	}
	project, ok := value["project"].(map[string]any)
	if !ok || len(project) != 1 {
		return false
	}
	_, ok = project["name"].(string)
	return ok
}

func safeSetupTarget(path string) bool {
	if path == "AGENTS.md" || path == "CLAUDE.md" || path == ".harness/harness.yaml" {
		return true
	}
	parts := strings.Split(filepath.ToSlash(path), "/")
	return len(parts) == 4 && parts[0] == ".harness" && parts[1] == "skills" && parts[3] == "SKILL.md" && application.ValidateID(parts[2]) == nil
}

func writeSetupPlan(ctx context.Context, root string, files []setupOutputFile) (err error) {
	rootInfo, rootErr := os.Lstat(root)
	if rootErr != nil {
		return rootErr
	}
	if !rootInfo.IsDir() || rootInfo.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("project directory changed after preview")
	}
	var written []setupOutputFile
	defer func() {
		if err == nil {
			return
		}
		for index := len(written) - 1; index >= 0; index-- {
			file := written[index]
			path := filepath.Join(root, filepath.FromSlash(file.Path))
			if file.Replace {
				_ = replaceSetupFile(path, file.Original)
			} else {
				_ = os.Remove(path)
			}
		}
	}()
	for _, file := range files {
		if err := ctx.Err(); err != nil {
			return err
		}
		path := filepath.Join(root, filepath.FromSlash(file.Path))
		parent := filepath.ToSlash(filepath.Dir(file.Path))
		if parent != "." {
			if _, err := securityboundary.PrepareDirectory(root, parent); err != nil {
				return err
			}
		}
		current, readErr := os.ReadFile(path)
		if file.Replace {
			if readErr != nil || !bytes.Equal(current, file.Original) {
				return fmt.Errorf("%s changed after preview; no new content written to it", file.Path)
			}
			if err := replaceSetupFile(path, file.Content); err != nil {
				return err
			}
		} else {
			if !os.IsNotExist(readErr) {
				return fmt.Errorf("%s appeared after preview; refusing to overwrite it", file.Path)
			}
			stream, openErr := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
			if openErr != nil {
				return openErr
			}
			_, writeErr := stream.Write(file.Content)
			closeErr := stream.Close()
			if writeErr != nil || closeErr != nil {
				_ = os.Remove(path)
				if writeErr != nil {
					return writeErr
				}
				return closeErr
			}
		}
		written = append(written, file)
	}
	return nil
}

func replaceSetupFile(path string, content []byte) error {
	stream, err := os.CreateTemp(filepath.Dir(path), "harnessforge-setup-*")
	if err != nil {
		return err
	}
	temporary := stream.Name()
	defer os.Remove(temporary)
	if _, err := stream.Write(content); err != nil {
		stream.Close()
		return err
	}
	if err := stream.Close(); err != nil {
		return err
	}
	return safefile.Replace(temporary, path)
}
