package infrastructure

var spanish = map[string]string{
	"root.short":                 "HarnessForge crea y mantiene configuraciones para agentes de programación",
	"version.short":              "Mostrar la versión de HarnessForge",
	"init.short":                 "Crear la configuración inicial del harness",
	"analyze.short":              "Analizar un repositorio",
	"ask.short":                  "Consultar un proveedor de IA",
	"config.short":               "Gestionar preferencias del usuario (las credenciales quedan en variables de entorno)",
	"config.set.short":           "Guardar el proveedor de IA predeterminado",
	"config.get.short":           "Mostrar el proveedor de IA predeterminado",
	"validate.short":             "Validar un archivo YAML de Harness IR editado manualmente",
	"review.short":               "Revisar una regla conservando el formato manual del YAML",
	"context.short":              "Inspeccionar el contexto del modelo",
	"context.explain.short":      "Explicar la selección del contexto del repositorio",
	"skill.short":                "Descubrir procedimientos revisados del repositorio",
	"skill.discover.short":       "Proponer procedimientos de desarrollo recurrentes",
	"skill.generate.short":       "Generar una habilidad aprobada",
	"eval.short":                 "Evaluar recuperación y respuestas fundamentadas",
	"eval.run.short":             "Ejecutar una evaluación determinista",
	"eval.compare.short":         "Comparar informes de evaluación",
	"doctor.short":               "Diagnosticar el estado del harness sin modificar archivos",
	"github.short":               "Leer discusiones de GitHub sin modificarlas",
	"github.learn.short":         "Extraer conocimiento revisable de GitHub",
	"drift.short":                "Comparar reglas aprobadas del harness con un repositorio sin modificar ninguno",
	"embedding.short":            "Crear y comparar embeddings independientes",
	"embedding.create.short":     "Crear un embedding para un texto corto",
	"embedding.similarity.short": "Calcular similitud coseno",
	"symbols.short":              "Extraer símbolos estructurales del código",
	"output.created":             "Creado %s\n",
	"output.exists":              "%s ya existe; el archivo no se modificó. Ejecute `harnessforge validate --repository .` para comprobarlo.\n",
	"output.next_steps":          "Edite .harness/harness.yaml y ejecute `harnessforge validate --repository .` y `harnessforge generate codex --repository .`.\n",
	"output.valid":               "Harness IR válido: %s\n",
	"output.rule":                "Regla %s: %s\n",
	"output.skill":               "Habilidad generada %s\n",
	"error.unsupported_format":   "formato no compatible %q",
}

var presentationES = map[string]string{
	"Help about any command":                                                       "Ayuda sobre cualquier comando",
	"Generate the autocompletion script for the specified shell":                   "Generar el script de autocompletado para el shell especificado",
	"Language for CLI help and common output (en, pt-BR or es)":                    "Idioma de ayuda y mensajes comunes (en, pt-BR o es)",
	"Include Git repository metadata":                                              "Incluir metadatos Git del repositorio",
	"Output format: text or json":                                                  "Formato de salida: text o json",
	"Verify evidence files and literal symbols in this repository":                 "Verificar archivos de evidencia y símbolos literales en este repositorio",
	"Repository to inspect without modifying it":                                   "Repositorio a inspeccionar sin modificarlo",
	"Verify evidence against this repository without modifying it":                 "Verificar evidencia en este repositorio sin modificarlo",
	"Print reviewable correction proposals without applying them":                  "Mostrar propuestas de corrección para revisión sin aplicarlas",
	"Harness YAML file":                                                            "Archivo YAML del harness",
	"Model override":                                                               "Modelo alternativo",
	"Override saved provider":                                                      "Sustituir el proveedor guardado",
	"Output: text or validated json":                                               "Salida: text o json validado",
	"Include selected repository context as evidence (JSON only)":                  "Incluir contexto del repositorio como evidencia (solo JSON)",
	"Maximum estimated tokens for repository context; 0 selects the model default": "Máximo estimado de tokens para el contexto; 0 selecciona el valor predeterminado del modelo",
	"Print repository context selection and do not call the provider":              "Mostrar la selección de contexto sin consultar al proveedor",
	"Stream text as it arrives":                                                    "Transmitir texto a medida que llega",
	"Model name used to choose the default budget":                                 "Nombre del modelo para elegir el presupuesto predeterminado",
	"Confirm human review of this proposal":                                        "Confirmar revisión humana de esta propuesta",
	"Environment variable containing a GitHub token":                               "Variable de entorno que contiene un token de GitHub",
}
