package infrastructure

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"harnessforge/internal/generation/domain"
	"harnessforge/internal/safefile"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "<!-- Generated by HarnessForge. Review Harness IR before regenerating. -->"
const ownershipFile = ".harnessforge-generated-hashes"

type Markdown struct{ Agent string }

func (m Markdown) Render(input domain.Input) (domain.Document, error) {
	path := "AGENTS.md"
	if m.Agent == "claude" {
		path = "CLAUDE.md"
	} else if m.Agent != "codex" {
		return domain.Document{}, fmt.Errorf("unsupported agent %q", m.Agent)
	}
	rules := append([]domain.Rule(nil), input.Rules...)
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })
	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\n# %s agent instructions\n\n", marker, input.Project)
	if len(rules) > 0 {
		out.WriteString("## Approved rules\n\n")
		for _, r := range rules {
			fmt.Fprintf(&out, "- [%s] %s", r.ID, r.Description)
			if len(r.Paths) > 0 {
				fmt.Fprintf(&out, " (scope: %v)", r.Paths)
			}
			out.WriteByte('\n')
		}
	}
	if len(input.Skills) > 0 {
		skills := append([]domain.Skill(nil), input.Skills...)
		sort.Slice(skills, func(i, j int) bool { return skills[i].ID < skills[j].ID })
		out.WriteString("\n## Skills\n\n")
		for _, skill := range skills {
			fmt.Fprintf(&out, "- [%s] %s", skill.ID, skill.Description)
			if skill.Path != "" {
				fmt.Fprintf(&out, " (reference: `%s`)", skill.Path)
			}
			out.WriteByte('\n')
		}
	}
	if len(input.Gates) > 0 {
		out.WriteString("\n## Quality commands\n\n")
		for _, gate := range input.Gates {
			fmt.Fprintf(&out, "- [%s] `%s`", gate.ID, gate.Command)
			if gate.Workspace != "" {
				fmt.Fprintf(&out, " (workspace: `%s`)", gate.Workspace)
			}
			if len(gate.Workspaces) > 0 {
				fmt.Fprintf(&out, " (workspaces: `%s`)", strings.Join(gate.Workspaces, "`, `"))
			}
			out.WriteByte('\n')
		}
	}
	if len(input.Policies) > 0 {
		policies := append([]domain.Policy(nil), input.Policies...)
		sort.Slice(policies, func(i, j int) bool { return policies[i].ID < policies[j].ID })
		out.WriteString("\n## Policy capability notes\n\n")
		for _, policy := range policies {
			fmt.Fprintf(&out, "- [%s] %s — capability: **%s**; executor: %s. This instruction text does not enforce system permissions.\n", policy.ID, policy.Description, policy.Capability, policy.Executor)
		}
	}
	return domain.Document{Path: path, Content: out.Bytes()}, nil
}

type FileWriter struct{}

func (FileWriter) Write(ctx context.Context, root string, document domain.Document) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		return fmt.Errorf("repository must be a directory")
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return err
	}
	if document.Path != "AGENTS.md" && document.Path != "CLAUDE.md" {
		return fmt.Errorf("unsupported generated document path")
	}
	if len(document.Content) > 1<<20 {
		return fmt.Errorf("generated document exceeds 1 MiB")
	}
	path := filepath.Join(root, document.Path)
	if target, err := os.Lstat(path); err == nil && target.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing to replace symlink %s", document.Path)
	}
	var previousHash string
	manifestPath := filepath.Join(root, ownershipFile)
	if raw, readErr := os.ReadFile(manifestPath); readErr == nil {
		previousHash = parseOwnedHash(raw, document.Path)
	} else if !os.IsNotExist(readErr) {
		return readErr
	}
	existing, readErr := os.ReadFile(path)
	if readErr == nil {
		hash := sha256.Sum256(existing)
		if previousHash == "" || previousHash != hex.EncodeToString(hash[:]) {
			return fmt.Errorf("refusing to overwrite manually edited or unowned %s", document.Path)
		}
	} else if !os.IsNotExist(readErr) {
		return readErr
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(root, "harnessforge-generated-*")
	if err != nil {
		return err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if _, err = temporary.Write(document.Content); err == nil {
		err = temporary.Close()
	}
	if err != nil {
		return err
	}
	if err := safefile.Replace(name, path); err != nil {
		return err
	}
	return writeOwnedHash(root, document.Path, document.Content)
}

func parseOwnedHash(data []byte, path string) string {
	for _, line := range bytes.Split(data, []byte{'\n'}) {
		parts := bytes.SplitN(line, []byte{' '}, 2)
		if len(parts) == 2 && string(parts[1]) == path {
			return string(parts[0])
		}
	}
	return ""
}

func writeOwnedHash(root, path string, content []byte) error {
	manifestPath := filepath.Join(root, ownershipFile)
	var entries = map[string]string{}
	if raw, err := os.ReadFile(manifestPath); err == nil {
		for _, line := range bytes.Split(raw, []byte{'\n'}) {
			parts := bytes.SplitN(line, []byte{' '}, 2)
			if len(parts) == 2 && len(parts[0]) == sha256.Size*2 {
				entries[string(parts[1])] = string(parts[0])
			}
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	hash := sha256.Sum256(content)
	entries[path] = hex.EncodeToString(hash[:])
	paths := make([]string, 0, len(entries))
	for name := range entries {
		paths = append(paths, name)
	}
	sort.Strings(paths)
	var out bytes.Buffer
	for _, name := range paths {
		fmt.Fprintf(&out, "%s %s\n", entries[name], name)
	}
	file, err := os.CreateTemp(root, "harnessforge-ownership-*")
	if err != nil {
		return err
	}
	tmp := file.Name()
	defer os.Remove(tmp)
	if _, err = file.Write(out.Bytes()); err == nil {
		err = file.Close()
	}
	if err != nil {
		return err
	}
	return safefile.Replace(tmp, manifestPath)
}
