package infrastructure

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"harnessforge/internal/generation/domain"
	"harnessforge/internal/safefile"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

const marker = "<!-- Generated by HarnessForge. Review Harness IR before regenerating. -->"
const ownershipFile = ".harnessforge-generated-hashes"

type Markdown struct{ Agent string }

func (m Markdown) Render(input domain.Input) (domain.Document, error) {
	path := "AGENTS.md"
	if m.Agent == "claude" {
		path = "CLAUDE.md"
	} else if m.Agent != "codex" {
		return domain.Document{}, fmt.Errorf("unsupported agent %q", m.Agent)
	}
	return m.renderAt(input, path, nil)
}

func (m Markdown) renderAt(input domain.Input, outputPath string, nativeScopes map[string]string) (domain.Document, error) {
	rules := append([]domain.Rule(nil), input.Rules...)
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })
	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\n# %s agent instructions\n\n", marker, input.Project)
	if input.Summary != "" || input.Notes != "" || len(input.Documents) > 0 {
		out.WriteString("## Project context\n\n")
		if input.Summary != "" {
			fmt.Fprintf(&out, "%s\n\n", input.Summary)
		}
		if input.Notes != "" {
			fmt.Fprintf(&out, "Team observations:\n\n%s\n\n", input.Notes)
		}
		if len(input.Documents) > 0 {
			out.WriteString("Additional documents considered during setup:\n\n")
			for _, document := range input.Documents {
				fmt.Fprintf(&out, "- `%s`\n", document)
			}
			out.WriteByte('\n')
		}
	}
	if len(input.Architecture) > 0 {
		styles := append([]string(nil), input.Architecture...)
		sort.Strings(styles)
		out.WriteString("## Architecture\n\n")
		for _, style := range styles {
			fmt.Fprintf(&out, "- %s\n", style)
		}
		out.WriteByte('\n')
	}
	if len(rules) > 0 {
		if m.Agent == "codex" {
			out.WriteString("## Scope and precedence\n\n")
			out.WriteString("- Rules without path scopes apply globally.\n")
			out.WriteString("- Directory subtree scopes are emitted as nested `AGENTS.md` files and are loaded when Codex runs with its current directory in that subtree. Codex combines ancestor instructions; HarnessForge does not resolve conflicts between them.\n")
			out.WriteString("- Other path globs retain their exact authored text and are advisory; Codex does not enforce file-glob matching from this export.\n")
			out.WriteString("- Global and directory-scoped rules coexist; conflicting rules require explicit reconciliation.\n\n")
		}
		if m.Agent == "codex" {
			out.WriteString("## Approved rules\n\n")
		} else {
			out.WriteString("## Global rules\n\n")
		}
		for _, r := range rules {
			fmt.Fprintf(&out, "- [%s] %s", r.ID, r.Description)
			if len(r.Paths) == 0 {
				out.WriteString(" (global)")
			} else if scope, ok := nativeScopes[r.ID]; ok {
				fmt.Fprintf(&out, " (native Codex directory scope: `%s`)", scope)
			} else if m.Agent == "claude" {
				return domain.Document{}, fmt.Errorf("Claude path-scoped rule %q requires RenderDocuments", r.ID)
			} else {
				fmt.Fprintf(&out, " (advisory; applies only to paths matching: %s)", formatScopeGlobs(r.Paths))
			}
			out.WriteByte('\n')
		}
	}
	if len(input.Skills) > 0 {
		skills := append([]domain.Skill(nil), input.Skills...)
		sort.Slice(skills, func(i, j int) bool { return skills[i].ID < skills[j].ID })
		out.WriteString("\n## Skills\n\n")
		for _, skill := range skills {
			fmt.Fprintf(&out, "- [%s] %s", skill.ID, skill.Description)
			if skill.Path != "" {
				fmt.Fprintf(&out, " (reference: `%s`)", skill.Path)
			}
			out.WriteByte('\n')
		}
	}
	if len(input.Gates) > 0 || len(input.Commands) > 0 {
		out.WriteString("\n## Quality commands\n\n")
		for _, gate := range input.Gates {
			fmt.Fprintf(&out, "- [%s] `%s`", gate.ID, gate.Command)
			if gate.Workspace != "" {
				fmt.Fprintf(&out, " (workspace: `%s`)", gate.Workspace)
			}
			if len(gate.Workspaces) > 0 {
				fmt.Fprintf(&out, " (workspaces: `%s`)", strings.Join(gate.Workspaces, "`, `"))
			}
			out.WriteByte('\n')
		}
		for _, command := range input.Commands {
			fmt.Fprintf(&out, "- `%s`\n", command)
		}
	}
	if len(input.Policies) > 0 {
		policies := append([]domain.Policy(nil), input.Policies...)
		sort.Slice(policies, func(i, j int) bool { return policies[i].ID < policies[j].ID })
		out.WriteString("\n## Policy capability notes\n\n")
		for _, policy := range policies {
			fmt.Fprintf(&out, "- [%s] %s — capability: **%s**; executor: %s. This instruction text does not enforce system permissions.\n", policy.ID, policy.Description, policy.Capability, policy.Executor)
		}
	}
	return domain.Document{Path: outputPath, Content: out.Bytes()}, nil
}

// codexDirectoryScope recognizes only a literal directory subtree glob. Codex
// discovers instructions by walking AGENTS.md files from project root to CWD;
// it does not implement arbitrary path-glob matching.
func codexDirectoryScope(scope string) (string, bool) {
	if scope == "**" {
		return "", true
	}
	if strings.Contains(scope, `\`) || !strings.HasSuffix(scope, "/**") {
		return "", false
	}
	directory := strings.TrimSuffix(scope, "/**")
	if directory == "" || path.IsAbs(directory) || path.Clean(directory) != directory {
		return "", false
	}
	for _, segment := range strings.Split(directory, "/") {
		if segment == "" || segment == "." || segment == ".." || strings.ContainsAny(segment, ":*?[]\"<>|") {
			return "", false
		}
		switch strings.ToLower(segment) {
		case ".git", ".hg", ".svn", ".forge", ".agents", ".claude":
			return "", false
		}
	}
	return directory, true
}

// RenderCodexDocuments returns the root instructions and native nested files
// for rules whose entire scope is representable as literal directory subtrees.
// A mixed or file-glob scope stays in the root document as explicitly advisory
// text; it is never broadened into a directory instruction.
func (CodexAdapter) RenderDocuments(input domain.Input) ([]domain.Document, error) {
	rootInput := input
	rootInput.Rules = nil
	nativeRoot := map[string]string{}
	nestedInputs := map[string][]domain.Rule{}
	nestedScopes := map[string]map[string]string{}

	for _, rule := range input.Rules {
		if len(rule.Paths) == 0 {
			rootInput.Rules = append(rootInput.Rules, rule)
			continue
		}
		directories := make([]string, 0, len(rule.Paths))
		fullyNative := true
		for _, scope := range rule.Paths {
			directory, ok := codexDirectoryScope(scope)
			if !ok {
				fullyNative = false
				break
			}
			directories = append(directories, directory)
		}
		if !fullyNative {
			rootInput.Rules = append(rootInput.Rules, rule)
			continue
		}
		directories = minimalScopeDirectories(directories)
		for _, directory := range directories {
			scope := "**"
			output := "AGENTS.md"
			if directory != "" {
				scope = directory + "/**"
				output = filepath.ToSlash(filepath.Join(directory, "AGENTS.md"))
			}
			if directory == "" {
				rootInput.Rules = append(rootInput.Rules, rule)
				nativeRoot[rule.ID] = scope
				continue
			}
			copy := rule
			copy.Paths = []string{scope}
			nestedInputs[output] = append(nestedInputs[output], copy)
			if nestedScopes[output] == nil {
				nestedScopes[output] = map[string]string{}
			}
			nestedScopes[output][rule.ID] = scope
		}
	}

	markdown := Markdown{Agent: "codex"}
	rootDoc, err := markdown.renderAt(rootInput, "AGENTS.md", nativeRoot)
	if err != nil {
		return nil, err
	}
	documents := []domain.Document{rootDoc}
	paths := make([]string, 0, len(nestedInputs))
	for path := range nestedInputs {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, output := range paths {
		nestedInput := domain.Input{Project: input.Project, Rules: nestedInputs[output]}
		doc, err := markdown.renderAt(nestedInput, output, nestedScopes[output])
		if err != nil {
			return nil, err
		}
		documents = append(documents, doc)
	}
	return documents, nil
}

func minimalScopeDirectories(directories []string) []string {
	sort.Strings(directories)
	unique := make([]string, 0, len(directories))
	for _, directory := range directories {
		if len(unique) > 0 && unique[len(unique)-1] == directory {
			continue
		}
		unique = append(unique, directory)
	}
	minimal := make([]string, 0, len(unique))
	for _, candidate := range unique {
		covered := false
		for _, parent := range unique {
			if parent == candidate || parent == "" {
				if parent == "" && candidate != "" {
					covered = true
				}
				continue
			}
			if strings.HasPrefix(candidate, parent+"/") {
				covered = true
				break
			}
		}
		if !covered {
			minimal = append(minimal, candidate)
		}
	}
	return minimal
}

func formatScopeGlobs(paths []string) string {
	return "`" + strings.Join(paths, "`, `") + "`"
}

type FileWriter struct{}

func (FileWriter) Write(ctx context.Context, root string, document domain.Document) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		return fmt.Errorf("repository must be a directory")
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return err
	}
	if document.Path != "AGENTS.md" && document.Path != "CLAUDE.md" {
		return fmt.Errorf("unsupported generated document path")
	}
	path := filepath.Join(root, document.Path)
	if target, err := os.Lstat(path); err == nil && target.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing to replace symlink %s", document.Path)
	}
	var previousHash string
	manifestPath := filepath.Join(root, ownershipFile)
	if raw, readErr := os.ReadFile(manifestPath); readErr == nil {
		previousHash = parseOwnedHash(raw, document.Path)
	} else if !os.IsNotExist(readErr) {
		return readErr
	}
	existing, readErr := os.ReadFile(path)
	if readErr == nil {
		hash := sha256.Sum256(existing)
		if previousHash != "" && previousHash != hex.EncodeToString(hash[:]) {
			return fmt.Errorf("refusing to overwrite manually edited or unowned %s", document.Path)
		}
		if previousHash == "" {
			boundary := bytes.Index(existing, []byte("\n\n"+marker))
			if boundary < 0 {
				return fmt.Errorf("refusing to overwrite manually edited or unowned %s", document.Path)
			}
			prefix := append([]byte(nil), existing[:boundary+2]...)
			document.Content = append(prefix, document.Content...)
		}
	} else if !os.IsNotExist(readErr) {
		return readErr
	}
	if len(document.Content) > 1<<20 {
		return fmt.Errorf("generated document exceeds 1 MiB")
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(root, "harnessforge-generated-*")
	if err != nil {
		return err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if _, err = temporary.Write(document.Content); err == nil {
		err = temporary.Close()
	}
	if err != nil {
		return err
	}
	if err := safefile.Replace(name, path); err != nil {
		return err
	}
	return writeOwnedHash(root, document.Path, document.Content)
}

func parseOwnedHash(data []byte, path string) string {
	for _, line := range bytes.Split(data, []byte{'\n'}) {
		parts := bytes.SplitN(line, []byte{' '}, 2)
		if len(parts) == 2 && string(parts[1]) == path {
			return string(parts[0])
		}
	}
	return ""
}

func writeOwnedHash(root, path string, content []byte) error {
	manifestPath := filepath.Join(root, ownershipFile)
	var entries = map[string]string{}
	if raw, err := os.ReadFile(manifestPath); err == nil {
		for _, line := range bytes.Split(raw, []byte{'\n'}) {
			parts := bytes.SplitN(line, []byte{' '}, 2)
			if len(parts) == 2 && len(parts[0]) == sha256.Size*2 {
				entries[string(parts[1])] = string(parts[0])
			}
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	hash := sha256.Sum256(content)
	entries[path] = hex.EncodeToString(hash[:])
	paths := make([]string, 0, len(entries))
	for name := range entries {
		paths = append(paths, name)
	}
	sort.Strings(paths)
	var out bytes.Buffer
	for _, name := range paths {
		fmt.Fprintf(&out, "%s %s\n", entries[name], name)
	}
	file, err := os.CreateTemp(root, "harnessforge-ownership-*")
	if err != nil {
		return err
	}
	tmp := file.Name()
	defer os.Remove(tmp)
	if _, err = file.Write(out.Bytes()); err == nil {
		err = file.Close()
	}
	if err != nil {
		return err
	}
	return safefile.Replace(tmp, manifestPath)
}
