package infrastructure

import (
	"bytes"
	"context"
	"fmt"
	"harnessforge/internal/generation/domain"
	"harnessforge/internal/safefile"
	"os"
	"path/filepath"
	"sort"
)

const marker = "<!-- Generated by HarnessForge. Review Harness IR before regenerating. -->"

type Markdown struct{ Agent string }

func (m Markdown) Render(input domain.Input) (domain.Document, error) {
	path := "AGENTS.md"
	if m.Agent == "claude" {
		path = "CLAUDE.md"
	} else if m.Agent != "codex" {
		return domain.Document{}, fmt.Errorf("unsupported agent %q", m.Agent)
	}
	rules := append([]domain.Rule(nil), input.Rules...)
	sort.Slice(rules, func(i, j int) bool { return rules[i].ID < rules[j].ID })
	var out bytes.Buffer
	fmt.Fprintf(&out, "%s\n# %s agent instructions\n\n", marker, input.Project)
	if len(rules) > 0 {
		out.WriteString("## Approved rules\n\n")
		for _, r := range rules {
			fmt.Fprintf(&out, "- [%s] %s", r.ID, r.Description)
			if len(r.Paths) > 0 {
				fmt.Fprintf(&out, " (scope: %v)", r.Paths)
			}
			out.WriteByte('\n')
		}
	}
	if len(input.Commands) > 0 {
		out.WriteString("\n## Quality commands\n\n")
		for _, command := range input.Commands {
			fmt.Fprintf(&out, "- `%s`\n", command)
		}
	}
	return domain.Document{Path: path, Content: out.Bytes()}, nil
}

type FileWriter struct{}

func (FileWriter) Write(ctx context.Context, root string, document domain.Document) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	root, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		return fmt.Errorf("repository must be a directory")
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return err
	}
	if document.Path != "AGENTS.md" && document.Path != "CLAUDE.md" {
		return fmt.Errorf("unsupported generated document path")
	}
	if len(document.Content) > 1<<20 {
		return fmt.Errorf("generated document exceeds 1 MiB")
	}
	path := filepath.Join(root, document.Path)
	if target, err := os.Lstat(path); err == nil && target.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("refusing to replace symlink %s", document.Path)
	}
	if existing, err := os.ReadFile(path); err == nil && !bytes.HasPrefix(existing, []byte(marker)) {
		return fmt.Errorf("refusing to overwrite manually owned %s", document.Path)
	} else if err != nil && !os.IsNotExist(err) {
		return err
	}
	temporary, err := os.CreateTemp(root, "harnessforge-generated-*")
	if err != nil {
		return err
	}
	name := temporary.Name()
	defer os.Remove(name)
	if _, err = temporary.Write(document.Content); err == nil {
		err = temporary.Close()
	}
	if err != nil {
		return err
	}
	return safefile.Replace(name, path)
}
